### PR TITLE
Solve task A exercise 2

### PR DESCRIPTION
**Pull request by legendofa**

### CODE REVIEW

**Review by Menkalian — CHANGES_REQUESTED** [review]
Unfortunately the commit message is a little bit too generic.
Please amend and change the message.

From the task:
 > use appropriate commit messages (**not** `Solve task A`)

**Comment by Menkalian** [comment]
That comment would also apply to the first pull-request, but since I did not catch it there, we have to leave it in the history. Should be bearable.

**Comment by legendofa** [comment]
> Unfortunately the commit message is a little bit too generic. Please amend and change the message.
> 
> From the task:
> 
> > use appropriate commit messages (**not** `Solve task A`)

Should be fixed now with a suitable commit message

**Review by Menkalian — APPROVED** [review]
Implementation + Tests look good

**Pull request merged**
